services:
  budgetzen_db:
    container_name: budgetzen_db
    image: postgres:15
    environment:
      - POSTGRES_USER=${POSTGRESQL_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRESQL_PASSWORD:-fake}
      - POSTGRES_DB=${POSTGRESQL_DBNAME:-budgetzen}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - budgetzen
    restart: unless-stopped

  budgetzen_web:
    container_name: budgetzen_web
    image: ghcr.io/brunobernardino/budgetzen-web:main
    # If you want to build the image locally, uncomment the
    # following lines and comment the image line above
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    ports:
      - ${PORT:-8000}:8000
    networks:
      - budgetzen
    restart: unless-stopped
    environment:
    - BASE_URL=${BASE_URL:-http://localhost:${PORT:-8000}}
    - POSTGRESQL_HOST=${POSTGRESQL_HOST:-budgetzen_db}
    - POSTGRESQL_USER=${POSTGRESQL_USER:-postgres}
    - POSTGRESQL_PASSWORD=${POSTGRESQL_PASSWORD:-fake}
    - POSTGRESQL_DBNAME=${POSTGRESQL_DBNAME:-budgetzen}
    - POSTGRESQL_PORT=${POSTGRESQL_PORT:-5432}
    - POSTGRESQL_CAFILE=${POSTGRESQL_CAFILE:-}
    - BREVO_API_KEY=${BREVO_API_KEY:-}
    - STRIPE_API_KEY=${STRIPE_API_KEY:-}
    
    # any non-empty value will be considered true
    - IS_UNSAFE_SELF_HOSTED="true"

    depends_on:
      - budgetzen_db

networks:
  budgetzen:

volumes:
  pgdata:
    driver: local
